### ISSUE TITLE
REQUEST:  Non-login users when run as root

### ISSUE THREAD

**Issue by DocSalvager** [MX-Linux/mx-user#11]
Since mx-user allows creation of "nologin" users, would like those users to appear in the various user selection dropdowns. As it is, only the users with /home directories appear in the dropdowns. To make changes to nologin users, must revert to commandline.

(As for the "Do not use GUIs as root" argument... I've been programming Unix/Linux computers for over 40 years. Worrying about X security is like worrying about burglars tracking dirt on your carpet. There are much more important security issues to worry about.)

**Comment by AdrianTM** [comment]
This is outside the scope of this tool. Besides, if I list all the users of a system people will start to delete them without understanding the consequences, for some things CLI is better (I know matter of debate)
