### ISSUE TITLE
 New versions 2024.06.15 and 2024.06.30 fail to create new users properly.

### ISSUE THREAD

**Issue by Mi605** [MX-Linux/mx-user#12]
Finding the Issue still not fixed in 2024.06.30. This renders the program unusable for most unexperienced users. Known workaround is to create new users on console manually, which does work flawlessly.

**Issue description**
After creating the user and the GUI coming up with the pop-up message the user was created OK, the new user can't log in to the system.
Error message at slimski login-screen is:

```
Authentification failed.

```

Issue is reproducible.
Issue is present on 32 bit and 64 bit systems both.

**Additional Info:**
Version 2023.07.08 doesn't have this issue. All user-accounts created by the old version do work properly. Copying over the old executable manually extracted from another system or from the old package to /usr/local/bin after upgrading to the new failing version, restores the ability to create new users on GUI properly immediately, so the issue can be narrowed down to the new executable itself.

Please see https://github.com/timkb4cq/mx-user/issues/24 for more details.

Original bug report for 2024.06.15 went to this place, since _apt-cache show_ returns:

```
Homepage: https://github.com/timkb4cq/mx-user
Original-Maintainer: adrian <adrian@mxlinux.org>
```

At least the 2024.06.30 version returns an error on console (not sure whether this is also present on 2024-06.15) :
```
...
QProcess: Destroyed while process ("/usr/bin/gksu") is still running.
...

```
**Scope:**
This affects all antiX versions which get one of the current versions of this tool by upgrading the system from the repos. 

Observed and tested on antiX 23, 23.1, 23.2. with different 5.x and 6.x kernels, including most recent debian vanilla kernels. Probably same on 22 and 21.

Please let me know whether you need more pieces of information about the testing systems. But I guess the most easy way to see the issue yourself is booting live into the current antiX 23.2-testing ISO and creating a new user from within Control centre, section Maintenance, User management.

**See also:**
https://www.antixforum.com/forums/topic/antix-23-2-full-runit-isos-for-testing/page/7/#post-147396 and https://www.antixforum.com/forums/topic/antix-23-2-full-runit-isos-for-testing/page/7/#post-147414

From the latter I read there is a temporary workaround available at https://drive.proton.me/urls/RCGXWB9EVR#0uF9ObGuslYK
but I reckon this issue can be fixed for upcoming versions in general, so not each new upcoming version breaks user systems again and again. Best would probably be not to destroy the gksu process before it has completed its job.

**Comment by Mi605** [comment]
The temporary workaround mentioned above doesn't work on 32 bit systems unfortunately. New users still not able to login when created by this tool in GUI. Please see https://www.antixforum.com/forums/topic/antix-23-2-full-runit-isos-for-testing/page/15/#post-149030

**Comment by AdrianTM** [comment]
I don't see this problem on MX, it's an antiX problem with a tool that is maintained by antiX, called antix-user. Please report it on their repo.
